/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_UserCheckerJNI */

#ifndef _Included_src_UserCheckerJNI
#define _Included_src_UserCheckerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_UserCheckerJNI
 * Method:    checkUsernameExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_src_UserCheckerJNI_checkUsernameExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     src_UserCheckerJNI
 * Method:    checkEmailExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_src_UserCheckerJNI_checkEmailExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     src_UserCheckerJNI
 * Method:    checkPhoneNumberExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_src_UserCheckerJNI_checkPhoneNumberExists
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
